.\"             -*-Nroff-*-
.\"
.TH "addinclude" 1 "16 Nov 2017" "" ""
.SH NAME
addinclude \- adds an include to a C or C++ header- or source file
.SH SYNOPSIS
.B addinclude
filename include
.SH DESCRIPTION
Addinclude provides a simple way to add includes to source or header files for C or C++.
.sp
Sometimes, a patch is overkill and search and replace does not cut it, due to include gards.
.sp
Addinclude adds the includes after the first #ifdef and preferrably together with the other #include lines.
.sp
If the header is empty, or there are no #ifdefs or #includes, the include is inserted at the top of the file.
.SH "EXAMPLES"
.B addinclude
- by itself returns errorcode 1 at exit
.sp
.B addinclude file.h '#include <string.h>'
- adds #include <string.h> to file.h
.sp
.B addinclude file.h stdlib
- adds #include <stdlib.h> to file.h
.sp
.B addinclude file.h \'"some.h"\'
- adds #include "some.h" to file.h
.sp
.B addinclude --nofix file.h \'"#include <some>"\'
- don't change the include text
.sp
.B addinclude --top file.h \'"#include <firstpost.h>"\'
- place the include at the top
.sp
.B addinclude --c++ file.cpp memory
- adds #include <memory> to file.cpp
.sp
.B addinclude --test
- performs self-testing
.PP
.SH OPTIONS
.TP
.B \-\-version or \-v
displays the current version number
.TP
.B \-\-help or \-h
displays brief informative text about usage
.TP
.B \-\-nofix or \-n
don't change the given include text
.TP
.B \-\-top or \-t
add the include at the very top
.TP
.B \-\-c++ or \-+
don't add .h to the include name
.TP
.B \-\-verbose or \-V
slightly more verbose output
.PP
.SH "WHY"
.sp
Aims to solve a tiny problem properly instead of a thousand problems halfway, in true UNIX-spirit
.sp
Makes a common case easy to solve
.sp
Has clear syntax
.sp
Is only one small executable, not a big package
.SH "SEE ALSO"
.BR sed (1)
.SH VERSION
1.0
.SH BUGS
Only unknown bugs so far.
.SH AUTHOR
.B addinclude
was written by Alexander F Rødseth <xyproto@archlinux.org>.
